INSERT INTO paquetes (nombre, descripcion, precio, imagen_url, disponibilidad, ubicacion, fecha_inicio, fecha_fin) VALUES
('Canal de Panamá', 'Visita al famoso Canal de Panamá, una maravilla de la ingeniería que conecta el Océano Atlántico con el Pacífico.', 150.00, 'http://localhost/proyectofinal/images/canal-panama.jpg', 1, 'Panamá', '2024-12-01', '2025-01-01'),
('Casco Antiguo', 'Recorrido histórico por el Casco Viejo de la ciudad, patrimonio mundial de la UNESCO.', 50.00, 'http://localhost/proyectofinal/images/casco-antiguo.jpg', 1, 'Panamá', '2024-12-05', '2025-01-05'),
('Bocas del Toro', 'Disfruta de las playas paradisíacas, actividades acuáticas y la rica biodiversidad de Bocas del Toro.', 300.00, 'http://localhost/proyectofinal/images/bocas-del-toro.jpg', 1, 'Bocas del Toro', '2025-01-10', '2025-02-10'),
('Boquete', 'Explora las montañas, cascadas y plantaciones de café en el fresco clima de Boquete.', 200.00, 'http://localhost/proyectofinal/images/boquete.jpg', 1, 'Chiriquí', '2024-12-15', '2025-01-15'),
('Islas de San Blas', 'Descubre las hermosas islas de la comarca Guna Yala, con playas de arena blanca y agua cristalina.', 250.00, 'http://localhost/proyectofinal/images/san-blas.jpg', 1, 'Guna Yala', '2025-01-01', '2025-02-01'),
('Parque Nacional Soberanía', 'Caminata por el parque nacional donde se pueden avistar aves y disfrutar de la naturaleza.', 100.00, 'http://localhost/proyectofinal/images/parque-soberania.jpg', 1, 'Colón', '2024-12-20', '2025-01-20'),
('Taboga', 'Excursión de un día a la Isla Taboga, conocida como la Isla de las Flores, con hermosas playas y senderos.', 75.00, 'http://localhost/proyectofinal/images/taboga.jpg', 1, 'Panamá', '2024-12-25', '2025-01-25'),
('Volcán Barú', 'Aventura en el punto más alto de Panamá, con vistas espectaculares del amanecer sobre ambos océanos.', 120.00, 'http://localhost/proyectofinal/images/volcan-baru.jpg', 1, 'Chiriquí', '2025-01-15', '2025-02-15'),
('Playa Venao', 'Un destino perfecto para surfistas y amantes de las playas tranquilas y hermosas.', 180.00, 'http://localhost/proyectofinal/images/playa-venao.jpg', 1, 'Los Santos', '2024-12-18', '2025-01-18'),
('Cerro Ancón', 'Una caminata corta con una vista impresionante de la Ciudad de Panamá desde su cima.', 40.00, 'http://localhost/proyectofinal/images/cerro-ancon.jpg', 1, 'Panamá', '2024-12-10', '2025-01-10');
